update to miniforge
Open-MSS/mss-install pull request #20
Opened 2023-12-08 14:34 UTC by ReimarBauer

2023-12-08 16:37 UTC, ReimarBauer commented
A similar problem is shown on  https://github.com/mamba-org/mamba/issues/3044

2023-12-08 17:15 UTC, ReimarBauer commented
- [ ] manual linux installation succeeds. 
- [ ] manual windows installation

2023-12-12 11:04 UTC, ReimarBauer commented
tested on a guacamole win setup and a new linux user

2024-02-15 12:47 UTC, matrss requested changes
Just some missed action updates, otherwise this looks good to me. I didn't test locally though, but CI says it's good.

When squashing please clean up the commit message, otherwise the git log becomes an incomprehensible mess.

2024-02-15 12:47 UTC, matrss commented on .github/workflows/test_installer.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

Since you have changed in the other jobs as well.

2024-02-15 12:47 UTC, matrss commented on .github/workflows/test_installer.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-02-15 12:47 UTC, matrss commented on .github/workflows/test_installer.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-02-15 12:47 UTC, matrss commented on .github/workflows/test_installer.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-02-22 12:40 UTC, merged